apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo

resources:
  - namespace.yaml
  - bookinfo.yaml
  - httproutes.yaml

labels:
  - pairs:
      hostk8s.stack: book-app
      hostk8s.app: bookinfo

# Only productpage gets application label for clean status detection
patches:
  - target:
      name: productpage
      kind: Service
    patch: |-
      - op: add
        path: /metadata/labels/hostk8s.application
        value: bookinfo
