apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - database.yaml
  - restart.yaml

# Generate ConfigMap with foundation postgres database configuration (no hash for stable reference)
configMapGenerator:
  - name: pgadmin-servers-config
    namespace: postgres
    files:
      - servers.json
    options:
      disableNameSuffixHash: true

commonLabels:
  hostk8s.stack: postgres
  hostk8s.app: postgres-foundation
