apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - source.yaml
  - release.yaml

commonLabels:
  hostk8s.component: elasticsearch
  component.hostk8s.io/role: operator
