---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: flux-system
spec:
  targetNamespace: hostk8s
  releaseName: elastic-operator
  chart:
    spec:
      chart: eck-operator
      version: "2.15.0"  # ECK operator version 2.15.0 (contains ECK 3.1.0)
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  install:
    createNamespace: false  # hostk8s namespace already exists
    remediation:
      retries: 3
  interval: 10m0s
  values:
    # Watch all namespaces for Elasticsearch resources
    watchNamespaces: [""]

    # Resource limits for local development
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 150Mi

    # Webhook configuration
    webhook:
      enabled: true

    # Development-friendly settings
    config:
      containerRegistry: docker.elastic.co
      logVerbosity: 0  # Info level logging

    # Create RBAC resources
    createClusterScopedResources: true

    # Service account
    serviceAccount:
      name: elastic-operator
