# Default values for helm-sample voting app
# This is a YAML-formatted file.

# Global settings
global:
  labels:
    app: "{{ .Chart.Name }}"
    hostk8s.app: helm-sample

# Vote service configuration
vote:
  name: vote
  replicas: 2
  image:
    repository: dockersamples/examplevotingapp_vote
    tag: ""
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  env:
    optionA: "Cats"
    optionB: "Dogs"

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Redis configuration
redis:
  name: redis
  replicas: 1
  image:
    repository: redis
    tag: "alpine"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379

  resources:
    requests:
      memory: "32Mi"
      cpu: "25m"
    limits:
      memory: "64Mi"
      cpu: "50m"

# Worker configuration
worker:
  name: worker
  replicas: 1
  image:
    repository: dockersamples/examplevotingapp_worker
    tag: ""
    pullPolicy: IfNotPresent

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Database (PostgreSQL) configuration
db:
  name: db
  replicas: 1
  image:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432

  env:
    postgresPassword: "postgres"
    postgresUser: "postgres"
    postgresDb: "postgres"

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Result service configuration
result:
  name: result
  replicas: 1
  image:
    repository: dockersamples/examplevotingapp_result
    tag: ""
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: localhost
      paths:
        - path: /vote(/|$)(.*)
          pathType: ImplementationSpecific
          service: vote
        - path: /result(/|$)(.*)
          pathType: ImplementationSpecific
          service: result
  tls: []
