# Default values for advanced
# This is a YAML-formatted file.

# Global settings
global:
  labels:
    app: "{{ .Chart.Name }}"
    hostk8s.app: advanced

# Application configuration
app:
  title: "HostK8s Advanced Sample"
  vote1: "Kustomize"
  vote2: "Helm"
  showHost: false

# Frontend (Python Flask) configuration
frontend:
  name: advanced-front
  replicas: 1
  image:
    repository: neilpeterson/azure-vote-front
    tag: "v3"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"

# Backend (Redis) configuration
backend:
  name: advanced-back
  replicas: 1
  image:
    repository: redis
    tag: "alpine"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379

  env:
    allowEmptyPassword: "yes"

  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "100m"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: "*"
      paths:
        - path: /
          pathType: Prefix
          service: advanced-front
  tls: []
