######################
## Gateway API CRDs
## Required for Kubernetes native Gateway API support
######################
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.2.0  # Use stable version

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
  labels:
    hostk8s.component: istio
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: gateway-api
  path: ./config/crd/standard
  prune: false  # Never prune CRDs
  wait: true
  timeout: 2m
