apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  targetNamespace: istio-system
  releaseName: istiod
  dependsOn:
    - name: istio-base
      namespace: flux-system
  chart:
    spec:
      chart: istiod
      version: ">=1.24.0 <2.0.0"  # Auto-update minor versions
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    pilot:
      env:
        # Enable Gateway API support
        PILOT_ENABLE_GATEWAY_API: "true"
        PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER: "true"
        PILOT_ENABLE_GATEWAY_API_STATUS: "true"
        # Enable Ambient mode
        PILOT_ENABLE_AMBIENT: "true"
        PILOT_ENABLE_AMBIENT_CONTROLLERS: "true"
        # Development optimizations
        PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: "true"
        PILOT_ENABLE_CROSS_CLUSTER_WORKLOAD_ENTRY: "false"

      # Minimal resources for local development
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi

    # Global mesh configuration
    meshConfig:
      # Access logging to stdout for debugging
      accessLogFile: /dev/stdout
      # Disable telemetry by default for resource savings
      defaultConfig:
        proxyStatsMatcher:
          inclusionRegexps:
          - ".*outlier_detection.*"
          - ".*circuit_breakers.*"
        holdApplicationUntilProxyStarts: false
      # Default to plaintext for pod-to-pod (Ambient handles mTLS)
      defaultHttpRetryPolicy:
        attempts: 2
      extensionProviders:
      - name: prometheus
        envoyPrometheusRemoteService:
          service: prometheus.istio-system.svc.cluster.local
          port: 9090

    # Telemetry v2 configuration (minimal)
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              disable: true
            outboundSidecar:
              disable: true
            gateway:
              disable: false  # Keep gateway metrics
