stages:
  - integration-test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

test-docker-only:
  stage: integration-test
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - echo "Testing docker"
    - docker version
    - echo "Done"