# Simple GitLab CI test for hybrid approach
stages:
  - validate

validate-basic:
  stage: validate
  image: alpine:latest
  script:
    - echo "Testing basic GitLab CI validation approach"
    - ls -la
    - test -f Makefile
    - test -f README.md
    - test -d infra/scripts
    - test -d software
    - echo "✅ Basic validation passed"

validate-tools:
  stage: validate  
  image: alpine:latest
  before_script:
    - apk add --no-cache make bash
  script:
    - echo "Testing make targets"
    - make help
    - make -n up
    - make -n test
    - echo "✅ Make targets validated"