[registry."host.docker.internal:5002"]
  http = true
  insecure = true

[registry."localhost:5002"]
  http = true
  insecure = true

[registry."127.0.0.1:5002"]
  http = true
  insecure = true

[registry."localhost:5000"]
  http = true
  insecure = true
