apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry-alias
spec:
  selector:
    app: registry-core
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
