---
apiVersion: batch/v1
kind: Job
metadata:
  name: pgadmin-config-restart-sample
  namespace: postgres
  labels:
    hostk8s.app: sample-app
    hostk8s.component: postgres
    app.kubernetes.io/name: pgadmin-restart
spec:
  # Clean up job after completion
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        hostk8s.app: sample-app
    spec:
      restartPolicy: OnFailure
      serviceAccountName: pgadmin-restart
      containers:
      - name: restart-pgadmin
        image: bitnami/kubectl:latest
        command:
        - kubectl
        - rollout
        - restart
        - deployment/pgadmin4
        - -n
        - postgres
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
