apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: sample-app
  labels:
    app: vote
    hostk8s.component: vote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
        hostk8s.component: vote-service
    spec:
      containers:
      - name: vote
        image: localhost:5000/hostk8s-vote:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: OPTION_A
          value: "HostK8s Stack"
        - name: OPTION_B
          value: "HostK8s App"
        - name: REDIS_HOST
          value: "redis-master.redis.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
