apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-app
  labels:
    app: worker
    hostk8s.app: voting-app
    hostk8s.component: worker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        hostk8s.app: voting-app
        hostk8s.component: worker-service
    spec:
      containers:
      - name: worker
        image: localhost:5000/hostk8s-worker:latest
        env:
        - name: REDIS_HOST
          value: "redis.redis-infrastructure.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: POSTGRES_HOST
          value: "db.voting-app.svc.cluster.local"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "votes"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
