# Infrastructure Kustomization for OSDU-CI cluster
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: osdu-ci-self
  path: "./software/stamp/sources"
  prune: true
  wait: true
  timeout: 5m
