apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - source.yaml
  - external-secret.yaml
  - release.yaml
  - ingress.yaml
  # Note: create-admin-job.yaml should be deployed separately after Airflow is ready
