---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: flux-system
spec:
  targetNamespace: airflow
  releaseName: airflow
  chart:
    spec:
      chart: airflow
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: airflow-official
        namespace: flux-system
  install:
    createNamespace: false  # airflow namespace created by namespace.yaml
    remediation:
      retries: 3
  interval: 10m0s
  values:
    # Required for Flux deployments - disable Helm hooks for jobs
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false

    # Images
    images:
      airflow:
        repository: apache/airflow
        tag: "3.0.6"
        pullPolicy: IfNotPresent

    # Airflow configuration
    airflowVersion: "3.0.6"

    # Executor configuration - using LocalExecutor for development
    executor: "LocalExecutor"

    # Database configuration - using external PostgreSQL
    postgresql:
      enabled: false  # Use external PostgreSQL from postgres component

    # Redis configuration - not needed for LocalExecutor
    redis:
      enabled: false

    # External connections
    data:
      metadataSecretName: airflow-metadata  # Uses ExternalSecret template for connection string

    # Web server configuration
    webserver:
      enabled: true
      replicas: 1
      service:
        type: ClusterIP
        ports:
          - name: airflow-ui
            port: 8080

      # Default admin user - disabled to use init container instead
      defaultUser:
        enabled: false  # We'll create user via init container with secret

      # Resource limits - reduced for web UI only workload
      resources:
        limits:
          cpu: 500m
          memory: 512Mi  # Reduced from 1Gi - web UI doesn't need much
        requests:
          cpu: 100m
          memory: 128Mi

    # API Server configuration (separate component in Airflow Helm chart)
    apiServer:
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi  # Limit API server memory for development
        requests:
          cpu: 100m
          memory: 256Mi

    # Scheduler configuration - handles task execution with LocalExecutor
    scheduler:
      enabled: true
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi  # Reduced for development workload
        requests:
          cpu: 100m
          memory: 256Mi

    # Worker configuration - disabled for LocalExecutor
    workers:
      replicas: 0  # No workers needed with LocalExecutor

    # Triggerer configuration
    triggerer:
      enabled: true
      replicas: 1
      resources:
        limits:
          cpu: 200m
          memory: 256Mi  # Reduced for development
        requests:
          cpu: 50m
          memory: 128Mi

    # DAG Processor configuration
    dagProcessor:
      enabled: true
      replicas: 1
      resources:
        limits:
          cpu: 200m
          memory: 256Mi  # Reduced for development
        requests:
          cpu: 50m
          memory: 128Mi

    # StatsD configuration
    statsd:
      enabled: true
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi

    # Flower UI for Celery monitoring - not needed for LocalExecutor
    flower:
      enabled: false

    # DAGs configuration
    dags:
      gitSync:
        enabled: false  # We'll mount DAGs from persistent volume

      persistence:
        enabled: true
        existingClaim: "airflow-dags-pvc"
        accessMode: ReadWriteOnce
        size: 1Gi

    # Logs configuration
    logs:
      persistence:
        enabled: false

    # Config for Airflow
    config:
      core:
        load_examples: "False"  # Don't load example DAGs
        dags_folder: "/opt/airflow/dags"
        executor: "LocalExecutor"
        # Enable FAB auth manager for user management CLI commands (Airflow 3.x)
        auth_manager: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"

      webserver:
        expose_config: "True"  # Allow viewing config in UI (dev environment)
        enable_proxy_fix: "True"  # For ingress proxy
        base_url: "http://airflow.localhost"

      scheduler:
        # dag_dir_list_interval moved to dag_processor section for Airflow 3.x

      dag_processor:
        refresh_interval: 60  # Scan for new DAGs every 60 seconds

    # Security
    fernetKey: ""  # Will be set by ExternalSecret
    webserverSecretKey: ""  # Will be set by ExternalSecret

    # Create RBAC resources
    rbac:
      create: true
      createSCCRoleBinding: false  # Not needed for Kind

    # ServiceAccount
    serviceAccount:
      create: true
      name: airflow

    # Extra environment variables
    extraEnvVars:
      - name: AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS
        value: "False"
      - name: AIRFLOW__CORE__LOAD_EXAMPLES
        value: "False"
      - name: AIRFLOW__WEBSERVER__EXPOSE_HOSTNAME
        value: "True"
      - name: AIRFLOW__WEBSERVER__EXPOSE_STACKTRACE
        value: "True"  # For development

    # Labels
    labels:
      hostk8s.component: airflow
      hostk8s.type: workflow-orchestrator
