---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow
  labels:
    hostk8s.component: airflow
    hostk8s.type: dags-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: airflow-storage
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      hostk8s.storage.name: airflow-dags
