apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bookinfo
  namespace: flux-system
spec:
  targetNamespace: bookinfo
  releaseName: bookinfo
  chart:
    spec:
      chart: istio-bookinfo
      version: ">=1.0.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: bookinfo
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: 3
    createNamespace: false  # Namespace already created with Ambient mode
  upgrade:
    remediation:
      retries: 3
  values:
    # Enable all services
    productpage:
      enabled: true
      replicaCount: 1
      image:
        tag: "1.20.0"
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi

    details:
      enabled: true
      replicaCount: 1
      image:
        tag: "1.20.0"
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi

    reviews:
      enabled: true
      # Deploy all three versions for demonstrating traffic management
      versions:
        - name: v1
          replicaCount: 1
          image:
            tag: "1.20.0"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
        - name: v2
          replicaCount: 1
          image:
            tag: "1.20.0"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
        - name: v3
          replicaCount: 1
          image:
            tag: "1.20.0"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi

    ratings:
      enabled: true
      replicaCount: 1
      image:
        tag: "1.20.0"
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi

    # Service configuration
    service:
      type: ClusterIP  # Using Gateway API for ingress

    # Disable traditional ingress (using Gateway API instead)
    ingress:
      enabled: false
