apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-class.yaml
  - gateway-config.yaml
  - gateway.yaml
  - certificate.yaml

commonLabels:
  hostk8s.component: istio
  component.hostk8s.io/role: ingress
