apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: voting-db
  labels:
  hostk8s.app: sample-app

resources:
  - database.yaml
  - restart.yaml

# Generate ConfigMap with voting database configuration (no hash for stable reference)
configMapGenerator:
  - name: pgadmin-servers-config
    namespace: postgres
    files:
      - servers.json
    options:
      disableNameSuffixHash: true

commonLabels:
  hostk8s.app: sample-app
