######################
## Istio Stack
## Foundation stack for Istio service mesh with Bookinfo demo application
######################

---
# Infrastructure: cert-manager component
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-certs
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/certs
  prune: true
  wait: true

---
# Infrastructure: Istio service mesh
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-components
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-certs
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/istio
  prune: true
  wait: true

---
# Application: Bookinfo demo
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-app
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-components
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/stacks/foundation/istio/app
  prune: true
  wait: true
