apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo

resources:
  - namespace.yaml
  - bookinfo.yaml
  - httproutes.yaml

labels:
- pairs:
      hostk8s.stack: istio
      hostk8s.application: bookinfo

# Labels applied to all bookinfo resources via kustomization
