apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: redis
  annotations:
  component.hostk8s.io/description: "Redis infrastructure component with management UI"
  component.hostk8s.io/version: "1.0.0"

resources:
  - namespace.yaml
  - redis-deployment.yaml     # Using direct deployment instead of Helm due to Bitnami image issues
  - redis-commander.yaml      # Simple deployment for Redis Commander UI
  # - source.yaml             # Disabled: Bitnami chart sources
  # - release.yaml            # Disabled: HelmRelease with image issues
  - ingress.yaml
  - external-secret.yaml

# Note: commonLabels removed - they conflict with HelmRelease label management
# Labels should be managed directly in the HelmRelease values
