apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: redis
  annotations:
    component.hostk8s.io/description: "Redis infrastructure component with management UI"
    component.hostk8s.io/version: "1.0.0"

resources:
  - namespace.yaml
  - source.yaml
  - release.yaml

commonLabels:
  hostk8s.component: redis
