apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  namespace: redis
  labels:
    app: redis-commander
    hostk8s.component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
        hostk8s.component: redis
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: REDIS_HOSTS
          value: "local:redis:6379"
        - name: HTTP_USER
          valueFrom:
            secretKeyRef:
              name: redis-commander-credentials
              key: username
        - name: HTTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-commander-credentials
              key: password
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  namespace: redis
  labels:
    app: redis-commander
    hostk8s.component: redis
spec:
  selector:
    app: redis-commander
  ports:
  - port: 8081
    targetPort: 8081
    name: http
    nodePort: 30081
  type: NodePort
