apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  namespace: redis-infrastructure
  labels:
    hostk8s.component: redis-infrastructure
    app: redis-commander
    component: management-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
      component: management-ui
  template:
    metadata:
      labels:
        app: redis-commander
        component: management-ui
        hostk8s.component: redis-infrastructure
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: REDIS_HOSTS
          value: "redis://redis.redis-infrastructure.svc.cluster.local:6379"
        - name: REDIS_PASSWORD
          value: "devpassword"
        - name: HTTP_USER
          value: "admin"
        - name: HTTP_PASSWORD
          value: "admin"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
