apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  namespace: redis-infrastructure
  labels:
    hostk8s.component: redis-infrastructure
    app: redis-commander
    component: management-ui
spec:
  selector:
    app: redis-commander
    component: management-ui
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
    protocol: TCP
    name: http
  type: NodePort
