apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-infrastructure
  labels:
    hostk8s.component: redis-infrastructure
    app: redis
    component: server
spec:
  selector:
    app: redis
    component: server
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  type: ClusterIP
