apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis-infrastructure
  labels:
    hostk8s.component: redis-infrastructure
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: redis-bitnami
    namespace: flux-system
  values:
    # Architecture - simple replication for development
    architecture: standalone

    # Authentication - disable for development (matches current setup)
    auth:
      enabled: false

    # Master configuration
    master:
      service:
        name: redis  # Maintain current service name
        ports:
          redis: 6379
      persistence:
        enabled: true
        storageClass: "standard"
        size: 1Gi  # Match current setup
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"  # Match current setup
          cpu: "200m"
      livenessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        enabled: true
        initialDelaySeconds: 5
        periodSeconds: 5
      configuration: |
        # Redis configuration for HostK8s development (matches current config)
        bind 0.0.0.0
        port 6379

        # Persistence configuration
        save 900 1
        save 300 10
        save 60 10000

        # Memory management
        maxmemory 256mb
        maxmemory-policy allkeys-lru

        # Logging
        loglevel notice

    # Replica configuration (disabled for standalone)
    replica:
      replicaCount: 0

    # Network policy (enable for security)
    networkPolicy:
      enabled: true

    # Common labels
    commonLabels:
      hostk8s.component: redis-infrastructure
      app: redis
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-commander
  namespace: redis-infrastructure
  labels:
    hostk8s.component: redis-infrastructure
spec:
  interval: 5m
  dependsOn:
    - name: redis
      namespace: redis-infrastructure
  chart:
    spec:
      chart: ./k8s/helm-chart/redis-commander
      sourceRef:
        kind: GitRepository
        name: redis-commander
        namespace: flux-system
  values:
    # Service configuration (maintain current NodePort access)
    service:
      type: NodePort
      nodePort: 30081

    # Resources (match current setup)
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

    # Redis connection
    hosts: "redis:6379"  # Connect to Bitnami Redis service

    # Environment variables from secret
    env:
      HTTP_USER:
        valueFrom:
          secretKeyRef:
            name: redis-commander-credentials
            key: username
      HTTP_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: redis-commander-credentials
            key: password
      K8S_SIGTERM: "1"
