apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
  labels:
    hostk8s.component: redis-infrastructure
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: redis-commander
  namespace: flux-system
  labels:
    hostk8s.component: redis-infrastructure
spec:
  interval: 5m
  url: https://github.com/joeferner/redis-commander
  ref:
    branch: master
