kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: osdu-ci

networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  kubeProxyMode: "iptables"

nodes:
- role: control-plane
  image: kindest/node:v1.33.2
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        enable-admission-plugins: "NodeRestriction,ResourceQuota,LimitRanger,NamespaceLifecycle,ServiceAccount"
        request-timeout: "60s"

  extraPortMappings:
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  - containerPort: 30443
    hostPort: 8443
    protocol: TCP

  extraMounts:
  - hostPath: /tmp/kind-local-storage
    containerPath: /mnt/local-storage
    readOnly: false
