######################
## Ambient Mode Dataplane
## CNI plugin and ztunnel for L4 service mesh capabilities
######################

---
# Istio CNI Plugin (required for Ambient mode)
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  targetNamespace: istio-system
  releaseName: istio-cni
  dependsOn:
    - name: istiod
      namespace: flux-system
  chart:
    spec:
      chart: cni
      version: ">=1.24.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    profile: ambient
    cni:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 256Mi

---
# ZTunnel (Zero Trust Tunnel for L4 networking)
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: flux-system
spec:
  targetNamespace: istio-system
  releaseName: ztunnel
  dependsOn:
    - name: istio-cni
      namespace: flux-system
  chart:
    spec:
      chart: ztunnel
      version: ">=1.24.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    profile: ambient
    variant: distroless
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
    terminationGracePeriodSeconds: 30
