######################
## Istio Control Plane
## Base installation and istiod with Ambient + Gateway API profile
######################

---
# Istio Base (CRDs and foundational components)
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  targetNamespace: istio-system
  releaseName: istio-base
  chart:
    spec:
      chart: base
      version: ">=1.24.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  values:
    defaultRevision: default
    global:
      istioNamespace: istio-system

---
# Istio Control Plane (istiod)
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  targetNamespace: istio-system
  releaseName: istiod
  dependsOn:
    - name: istio-base
      namespace: flux-system
  chart:
    spec:
      chart: istiod
      version: ">=1.24.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Enable Ambient mode and Gateway API
    profile: ambient
    pilot:
      env:
        PILOT_ENABLE_GATEWAY_API: "true"
        PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER: "true"
        PILOT_ENABLE_GATEWAY_API_STATUS: "true"
        PILOT_ENABLE_AMBIENT: "true"
        PILOT_ENABLE_AMBIENT_CONTROLLERS: "true"
      # Minimal resources for local development
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    # Global mesh configuration
    meshConfig:
      accessLogFile: /dev/stdout
      defaultConfig:
        holdApplicationUntilProxyStarts: false
    # Simplified telemetry for Ambient mode
    telemetry:
      v2:
        enabled: true
        prometheus:
          service:
            enabled: true
