# Demo application with Ingress - showcases GitOps + Ingress integration
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-app
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "15.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: demo.local
      path: /
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "64Mi"
        cpu: "50m"
    # Custom welcome page
    serverBlock: |
      server {
        listen 8080;
        location / {
          return 200 '<!DOCTYPE html>
          <html><head><title>OSDU-CI GitOps Demo</title>
          <style>body{font-family:Arial;margin:40px;background:#f5f5f5}
          .container{max-width:600px;margin:0 auto;background:white;padding:30px;border-radius:8px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}
          h1{color:#2563eb;margin-bottom:20px}
          .status{background:#10b981;color:white;padding:8px 16px;border-radius:4px;display:inline-block;margin:10px 0}
          .info{background:#f3f4f6;padding:15px;border-radius:4px;margin:15px 0}
          </style></head>
          <body><div class="container">
          <h1>🚀 OSDU-CI GitOps Demo</h1>
          <div class="status">✅ Successfully deployed via Flux GitOps!</div>
          <div class="info">
          <strong>What you'\''re seeing:</strong><br/>
          • This app was deployed automatically by Flux<br/>
          • Flux monitors your Git repository for changes<br/>
          • NGINX Ingress Controller routes traffic to this app<br/>
          • Accessible via: <code>http://localhost:8080</code>
          </div>
          <p><strong>Next steps:</strong> Try modifying the GitOps configuration in <code>software/stamp/</code> and commit changes to see GitOps in action!</p>
          </div></body></html>';
          add_header Content-Type text/html;
        }
      }