# Components Layer - Infrastructure Services
# These are foundational services that applications consume
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference global components that this stamp needs
resources:
  - ../../components/cert-manager
  - ../../components/registry
