apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elasticsearch
  labels:
    hostk8s.component: elastic
  annotations:
    eck.k8s.alpha.elastic.co/propagate-labels: "hostk8s.component"
spec:
  version: 9.1.3

  # Disable TLS for local development
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: ClusterIP

  # Auth configuration - ECK will use elasticsearch-es-elastic-user secret from Vault

  nodeSets:
    - name: default
      count: 1  # Single node for development

      # Node configuration
      config:
        node.store.allow_mmap: false
        node.roles: ["master", "data", "ingest"]  # All roles on single node

      # Volume claim for data persistence - uses HostK8s storage contract
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: foundation-elastic-storage

      # Pod configuration
      podTemplate:
        metadata:
          labels:
            hostk8s.component: elastic
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms1g -Xmx1g"  # 1GB heap for development
              resources:
                requests:
                  memory: 2Gi
                  cpu: 100m
                limits:
                  memory: 2Gi
                  cpu: 1000m
