apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elasticsearch-es-elastic-user-vault
  namespace: elasticsearch
spec:
  refreshInterval: "0s"  # No refresh for dev environment
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: elasticsearch-es-elastic-user
    creationPolicy: Owner  # Create and manage the secret
    template:
      metadata:
        labels:
          eck.k8s.elastic.co/credentials: "true"
          eck.k8s.elastic.co/owner-kind: Elasticsearch
          eck.k8s.elastic.co/owner-name: elasticsearch
          eck.k8s.elastic.co/owner-namespace: elasticsearch
          elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
  data:
    - secretKey: elastic
      remoteRef:
        key: foundation/elastic/elasticsearch/elasticsearch-credentials
        property: elastic-password
