apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elasticsearch-credentials
  namespace: elasticsearch
spec:
  refreshInterval: "0s"  # No refresh for dev environment
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: elasticsearch-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: elastic-stack/elasticsearch/elasticsearch-credentials  # Path in Vault
