apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  labels:
    {{- include "helm-sample.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  type: {{ .Values.db.service.type }}
  ports:
  - port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.service.targetPort }}
    protocol: TCP
    name: postgres
  selector:
    {{- include "helm-sample.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
