apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.result.name }}
  labels:
    {{- include "helm-sample.labels" . | nindent 4 }}
    app.kubernetes.io/component: result
spec:
  type: {{ .Values.result.service.type }}
  ports:
  - port: {{ .Values.result.service.port }}
    targetPort: {{ .Values.result.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "helm-sample.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: result
