#!/bin/bash
# infra/scripts/show-help.sh - Cross-platform help display for Unix
echo "HostK8s - Host-Mode Kubernetes Development Platform"
echo ""
echo ""
echo "Usage:"
echo "  make <target>"
echo ""
echo "Setup"
echo "  help             Show this help message"
echo "  install          Install dependencies and setup environment (Usage: make install [dev])"
echo ""
echo "Infrastructure"
echo "  start            Start cluster (Usage: make start [config-name] - auto-discovers kind-*.yaml files)"
echo "  stop             Stop cluster"
echo "  up               Deploy software stack (Usage: make up [stack-name] - defaults to 'sample')"
echo "  down             Remove software stack (Usage: make down <stack-name>)"
echo "  restart          Quick cluster reset for development iteration (Usage: make restart [stack-name])"
echo "  clean            Complete cleanup (destroy cluster and data)"
echo "  status           Show cluster health and running services"
echo "  sync             Force Flux reconciliation (Usage: make sync [REPO=name] [KUSTOMIZATION=name])"
echo ""
echo "Applications"
echo "  deploy           Deploy application (Usage: make deploy [app-name] [namespace] - defaults to 'simple')"
echo "  remove           Remove application (Usage: make remove <app-name> [namespace] or NAMESPACE=ns make remove <app-name>)"
echo ""
echo "Development Tools"
echo "  logs             View recent cluster events and logs"
echo "  build            Build and push application from src/ (Usage: make build src/APP_NAME)"