# infra/scripts/show-help.ps1 - Cross-platform help display for Windows
Write-Host "HostK8s - Host-Mode Kubernetes Development Platform"
Write-Host ""
Write-Host ""
Write-Host "Usage:"
Write-Host "  make <target>"
Write-Host ""
Write-Host "Setup"
Write-Host "  help             Show this help message"
Write-Host "  install          Install dependencies and setup environment (Usage: make install [dev])"
Write-Host ""
Write-Host "Infrastructure"
Write-Host "  start            Start cluster (Usage: make start [config-name] - auto-discovers kind-*.yaml files)"
Write-Host "  stop             Stop cluster"
Write-Host "  up               Deploy software stack (Usage: make up [stack-name] - defaults to 'sample')"
Write-Host "  down             Remove software stack (Usage: make down <stack-name>)"
Write-Host "  restart          Quick cluster reset for development iteration (Usage: make restart [stack-name])"
Write-Host "  clean            Complete cleanup (destroy cluster and data)"
Write-Host "  status           Show cluster health and running services"
Write-Host "  sync             Force Flux reconciliation (Usage: make sync [REPO=name] [KUSTOMIZATION=name])"
Write-Host ""
Write-Host "Applications"
Write-Host "  deploy           Deploy application (Usage: make deploy [app-name] [namespace] - defaults to 'simple')"
Write-Host "  remove           Remove application (Usage: make remove <app-name> [namespace] or NAMESPACE=ns make remove <app-name>)"
Write-Host ""
Write-Host "Development Tools"
Write-Host "  logs             View recent cluster events and logs"
Write-Host "  build            Build and push application from src/ (Usage: make build src/APP_NAME)"