######################
## GitRepository Template for Stacks
## This creates a unique GitRepository for each stack: flux-system-${SOFTWARE_STACK}
## Applied by deploy-stack script with environment variable substitution
######################
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m
  url: https://community.opengroup.org/danielscholl/hostk8s
  ref:
    branch: main
  ignore: |
    exclude all
    !/software/components/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system-${SOFTWARE_STACK}
  namespace: flux-system
spec:
  interval: 5m
  url: ${GITOPS_REPO}
  ref:
    branch: ${GITOPS_BRANCH}
  ignore: |
    exclude all
    !/software/stacks/${SOFTWARE_STACK}/
