# PostgreSQL cluster for Airflow
# This ensures a postgres-cluster exists with the airflow database
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres
  labels:
    hostk8s.component: airflow
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "2GB"
      max_worker_processes: "2"
      max_parallel_workers_per_gather: "1"
      max_parallel_workers: "2"

  # Bootstrap configuration - create airflow database
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
      # Note: User and database creation handled manually to use generated passwords from secrets

  # Storage configuration
  storage:
    size: 5Gi
    storageClass: postgres-default

  # Resources for local development
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
