# Local Development Environment
# Use: docker-compose up
# Purpose: Develop and test sample-app without HostK8s

services:
  vote:
    build:
      context: ./vote
      target: dev
    ports:
      - "5000:80"
    volumes:
      - ./vote:/usr/local/app
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis

  result:
    build: ./result
    ports:
      - "5001:80"
    volumes:
      - ./result:/usr/local/app
      - /usr/local/app/node_modules  # Protect node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/votes
    depends_on:
      - db
    command: ["nodemon", "server.js"]

  worker:
    build: ./worker
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgres://postgres:password@db:5432/votes
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=votes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
