services:
  registry-demo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-}
        BUILD_VERSION: ${BUILD_VERSION:-1.0.0}
    image: localhost:5443/registry-demo:latest
    profiles:
      - build

  # Backward compatibility with HTTP registry
  registry-demo-http:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-}
        BUILD_VERSION: ${BUILD_VERSION:-1.0.0}
    image: localhost:5000/registry-demo:latest
    profiles:
      - build-http
