apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
  labels:
    osdu-ci.component: database
spec:
  interval: 1h
  releaseName: postgresql
  targetNamespace: database
  chart:
    spec:
      chart: postgresql
      version: "12.8.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      postgresPassword: "postgres"
      username: "appuser"
      password: "apppass"
      database: "appdb"
    primary:
      persistence:
        enabled: false
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
