apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
  labels:
    hostk8s.component: metrics-server
spec:
  interval: 1h
  releaseName: metrics-server
  targetNamespace: kube-system
  chart:
    spec:
      chart: metrics-server
      version: "3.12.1"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: kube-system
  values:
    args:
      - --cert-dir=/tmp
      - --secure-port=10250
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
      - --kubelet-insecure-tls
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
