######################
## Sample Stack Components
## These must complete before applications
######################
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: component-metrics-server
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/metrics-server
  prune: true
  wait: true
  healthChecks:
    - kind: Deployment
      name: metrics-server
      namespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: component-certs
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/certs
  prune: true
  wait: true
---
######################
## Ingress Controller
## Required for applications with ingress
######################
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: component-ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: component-certs
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/stacks/sample/ingress-nginx
  prune: true
  wait: true
  healthChecks:
    - kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
---
######################
## Sample Applications
## Deployed after infrastructure is ready
######################
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-sample
  namespace: flux-system
spec:
  dependsOn:
    - name: component-ingress-nginx
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/stacks/sample/app
  prune: true
  wait: true
  healthChecks:
    - kind: Deployment
      name: sample-api
      namespace: sample
    - kind: Deployment
      name: sample-website
      namespace: sample
