apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
  labels:
    hostk8s.component: database
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
