apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - database.yaml
  - restart.yaml

configMapGenerator:
  - name: pgadmin-servers-config
    namespace: postgres
    files:
      - servers.json
    options:
      disableNameSuffixHash: true

commonLabels:
  hostk8s.stack: airflow
  hostk8s.type: database
