---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgadmin-restart-airflow
  namespace: postgres
  labels:
    hostk8s.component: airflow

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pgadmin-restart-airflow
  namespace: postgres
  labels:
    hostk8s.component: airflow
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pgadmin-restart-airflow
  namespace: postgres
  labels:
    hostk8s.component: airflow
subjects:
- kind: ServiceAccount
  name: pgadmin-restart-airflow
  namespace: postgres
roleRef:
  kind: Role
  name: pgadmin-restart-airflow
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: Job
metadata:
  name: pgadmin-config-restart-airflow
  namespace: postgres
  labels:
    hostk8s.component: airflow
    app.kubernetes.io/name: pgadmin-restart-airflow
spec:
  # Clean up job after completion
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        hostk8s.component: airflow
    spec:
      restartPolicy: OnFailure
      serviceAccountName: pgadmin-restart-airflow
      containers:
      - name: restart-pgadmin
        image: bitnami/kubectl:latest
        command:
        - kubectl
        - rollout
        - restart
        - deployment/pgadmin4
        - -n
        - postgres
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
