apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stamp-${GITOPS_STAMP}-components
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: ${REPO_NAME}-repo
  path: ./software/stamp/${GITOPS_STAMP}/components
  prune: true
  wait: true
