apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - database.yaml

# Generate ConfigMap with hash suffix for automatic restart on changes
configMapGenerator:
  - name: pgadmin-servers-config
    files:
      - servers.json
    options:
      disableNameSuffixHash: false

# The configMapGenerator will automatically create a hash suffix
# When the ConfigMap content changes, the hash changes, and any deployment
# referencing it will be updated by Flux automatically

commonLabels:
  hostk8s.stack: postgres
  hostk8s.app: postgres-foundation
