apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - database.yaml

# ConfigMap generation moved to postgres-components for proper reference updates

commonLabels:
  hostk8s.stack: postgres
  hostk8s.app: postgres-foundation
