---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  labels:
    osdu-ci.component: cert-manager
spec:
  selfSigned: {}
---
# CA Issuer for creating a local CA certificate
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  labels:
    osdu-ci.component: cert-manager
spec:
  ca:
    secretName: ca-key-pair
