apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cert-manager shared component for local development
# Phase 1: Install cert-manager (CRDs, controllers)

resources:
  - namespace.yaml
  - source.yaml
  - release.yaml
  - issuer.yaml
