---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
    osdu-ci.component: cert-manager
    istio-injection: disabled
    toolkit.fluxcd.io/tenant: component
