apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sample-voting-app
  labels:
    hostk8s.app: sample

resources:
  - vote-deployment.yaml
  - vote-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - worker-deployment.yaml
  - db-deployment.yaml
  - db-service.yaml
  - result-deployment.yaml
  - result-service.yaml
  - ingress.yaml

commonLabels:
  hostk8s.app: sample
