apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  targetNamespace: istio-system
  releaseName: istio-cni
  dependsOn:
    - name: istiod
      namespace: flux-system
  chart:
    spec:
      chart: cni
      version: ">=1.24.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Enable Ambient mode profile
    profile: ambient

    # Resources optimized for local development
    cni:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 256Mi

    # Platform-specific configuration for Kind
    global:
      platform: ""  # Kind doesn't need special platform setting
