######################
## Waypoint Configuration
## Used for L7 processing in Ambient mode
## Note: istio-waypoint GatewayClass is automatically created by Istio
######################

# Configuration for waypoint proxies
apiVersion: v1
kind: ConfigMap
metadata:
  name: waypoint-config
  namespace: istio-system
data:
  # Waypoint configuration for resource-constrained environments
  deployment: |
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: istio-proxy
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
            env:
            - name: PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION
              value: "true"
            - name: ISTIO_META_ENABLE_HBONE
              value: "true"
