######################
## Waypoint GatewayClass
## Used for L7 processing in Ambient mode
######################
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: istio-waypoint
spec:
  controllerName: istio.io/waypoint
  description: Istio Waypoint proxy for L7 processing in Ambient mode
  parametersRef:
    group: ""
    kind: ConfigMap
    name: waypoint-config
    namespace: istio-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: waypoint-config
  namespace: istio-system
data:
  # Waypoint configuration for resource-constrained environments
  deployment: |
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: istio-proxy
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
            env:
            - name: PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION
              value: "true"
            - name: ISTIO_META_ENABLE_HBONE
              value: "true"
