apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
    hostk8s.component: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
        hostk8s.component: registry
    spec:
      containers:
      - name: registry
        image: registry:2.7
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_HEALTH_STORAGEDRIVER_ENABLED
          value: "true"
        # HTTP Configuration
        - name: REGISTRY_HTTP_ADDR
          value: ":5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
        livenessProbe:
          httpGet:
            path: /v2/
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v2/
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-data
