apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-data-pv
  labels:
    hostk8s.component: registry
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/local-storage/registry
    type: DirectoryOrCreate
