apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: registry
  labels:
    hostk8s.component: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: registry-data-pv
  resources:
    requests:
      storage: 10Gi
