apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
    hostk8s.component: registry
spec:
  selector:
    app: registry
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
---
# NodePort service for external access
apiVersion: v1
kind: Service
metadata:
  name: registry-nodeport
  namespace: registry
  labels:
    app: registry
    hostk8s.component: registry
spec:
  selector:
    app: registry
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30500
    protocol: TCP
  type: NodePort
