---
# Namespace for registry add-on
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    hostk8s.addon: registry

---
# Persistent Volume for registry storage (data/registry/)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-data-pv
  labels:
    hostk8s.addon: registry
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/registry
    type: DirectoryOrCreate

---
# Persistent Volume Claim for registry storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: registry
  labels:
    hostk8s.addon: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: registry-data-pv
  resources:
    requests:
      storage: 10Gi

---
# Registry Core Deployment (registry:2)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-core
  namespace: registry
  labels:
    app: registry-core
    hostk8s.addon: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-core
  template:
    metadata:
      labels:
        app: registry-core
        hostk8s.addon: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        - name: REGISTRY_LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /v2/
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v2/
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-data

---
# Registry Core Service (NodePort for direct access)
apiVersion: v1
kind: Service
metadata:
  name: registry-core
  namespace: registry
  labels:
    app: registry-core
    hostk8s.addon: registry
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30500
  selector:
    app: registry-core
