---
# Namespace for registry add-on
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    hostk8s.addon: registry

---
# Persistent Volume for registry storage (data/registry/)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-data-pv
  labels:
    hostk8s.addon: registry
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/registry
    type: DirectoryOrCreate

---
# Persistent Volume Claim for registry storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: registry
  labels:
    hostk8s.addon: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: registry-data-pv
  resources:
    requests:
      storage: 10Gi

---
# Registry Core Deployment (registry:2)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-core
  namespace: registry
  labels:
    app: registry-core
    hostk8s.addon: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-core
  template:
    metadata:
      labels:
        app: registry-core
        hostk8s.addon: registry
    spec:
      containers:
      - name: registry
        image: registry:2.8.3
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_HEALTH_STORAGEDRIVER_ENABLED
          value: "true"
        - name: REGISTRY_HTTP_ADDR
          value: ":5000"
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
        livenessProbe:
          httpGet:
            path: /v2/
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v2/
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-data

---
# Registry Core Service (NodePort for direct access)
apiVersion: v1
kind: Service
metadata:
  name: registry-core
  namespace: registry
  labels:
    app: registry-core
    hostk8s.addon: registry
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30500
  selector:
    app: registry-core

---
# Registry UI Deployment (Joxit)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: registry
  labels:
    app: registry-ui
    hostk8s.addon: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
        hostk8s.addon: registry
    spec:
      containers:
      - name: registry-ui
        image: joxit/docker-registry-ui:main
        ports:
        - containerPort: 80
          name: http
        env:
        - name: SINGLE_REGISTRY
          value: "true"
        - name: REGISTRY_TITLE
          value: "HostK8s Container Registry"
        - name: DELETE_IMAGES
          value: "true"
        - name: SHOW_CONTENT_DIGEST
          value: "true"
        - name: NGINX_PROXY_PASS_URL
          value: "http://registry-core.registry.svc.cluster.local:5000"
        - name: SHOW_CATALOG_NB_TAGS
          value: "true"
        - name: CATALOG_MIN_BRANCHES
          value: "1"
        - name: CATALOG_MAX_BRANCHES
          value: "1"
        - name: TAGLIST_PAGE_SIZE
          value: "100"
        - name: REGISTRY_SECURED
          value: "false"
        - name: CATALOG_ELEMENTS_LIMIT
          value: "1000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

---
# Registry UI Service (ClusterIP for ingress)
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: registry
  labels:
    app: registry-ui
    hostk8s.addon: registry
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: registry-ui

---
# Registry UI Ingress (conditional - only if ingress-nginx available)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ui
  namespace: registry
  labels:
    app: registry-ui
    hostk8s.addon: registry
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - host: registry.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: registry-ui
            port:
              number: 80
