######################
## Sample Stamp Components
######################
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stamp-sample-components
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: ${REPO_NAME}-repo
  path: ./software/stamp/sample/components
  prune: true
  wait: true

######################
## Sample Stamp Applications
######################
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stamp-sample-applications
  namespace: flux-system
spec:
  dependsOn:
    - name: stamp-sample-components
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: ${REPO_NAME}-repo
  path: ./software/stamp/sample/applications
  prune: true
  wait: true
