apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: simple
  labels:
    hostk8s.app: simple

labels:
- pairs:
    hostk8s.app: simple

resources:
  - deployment.yaml
  - configmap.yaml
  - service.yaml
  - ingress.yaml
