apiVersion: hostk8s.io/v1
kind: SecretContract
metadata:
  name: foundation/airflow
spec:
  secrets:
    # Airflow application secrets
    - name: airflow-secrets
      namespace: airflow
      data:
        - key: webserver-secret-key
          generate: password
          length: 32
        - key: fernet-key
          generate: fernet
        - key: admin-password
          generate: password
          length: 16
    # Airflow database credentials
    - name: airflow-db-credentials
      namespace: airflow
      data:
        - key: username
          value: airflow
        - key: password
          generate: password
          length: 16
        - key: host
          value: airflow-db-rw.postgres.svc.cluster.local
        - key: database
          value: airflow
    # pgAdmin4 web UI credentials (postgres component dependency)
    - name: pgadmin4-credentials
      namespace: postgres
      data:
        - key: email
          value: admin@hostk8s.com
        - key: password
          generate: password
          length: 12
    # Redis Commander web UI credentials (redis component dependency)
    - name: redis-commander-credentials
      namespace: redis
      data:
        - key: username
          value: admin
        - key: password
          generate: password
          length: 12
