apiVersion: hostk8s.io/v1
kind: SecretContract
metadata:
  name: foundation/airflow
spec:
  secrets:
    - name: airflow-secrets
      namespace: airflow
      data:
        - key: webserver-secret-key
          generate: password
          length: 32
        - key: fernet-key
          generate: fernet
        - key: admin-password
          generate: password
          length: 16
    - name: airflow-db-credentials
      namespace: airflow
      data:
        - key: username
          value: airflow
        - key: password
          generate: password
          length: 16
        - key: host
          value: postgres-cluster-rw.postgres.svc.cluster.local
        - key: database
          value: airflow
