apiVersion: hostk8s.io/v1
kind: StorageContract
metadata:
  name: foundation/airflow
  namespace: airflow
spec:
  directories:
    # PostgreSQL storage (component dependency)
    - name: postgres-default
      path: /mnt/pv/postgres
      size: 5Gi
      accessModes: ["ReadWriteOnce"]
      storageClass: postgres-default
      owner: "26:26"  # CloudNativePG PostgreSQL user/group
      permissions: "700"
    # Airflow DAGs storage
    - name: airflow-dags
      path: /mnt/pv/airflow-dags
      size: 1Gi
      accessModes: ["ReadWriteOnce"]
      storageClass: airflow-storage  # Custom StorageClass for immediate binding
      owner: "1000:1000"  # Airflow user/group
      permissions: "755"
