######################
## Airflow Stack
## Foundation stack for Apache Airflow with PostgreSQL and Redis
######################

---
# Application: Airflow component (self-contained with dependencies)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: foundation-airflow
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system-airflow
  path: ./software/components/airflow
  prune: true
  wait: true
  healthChecks:
    - kind: Deployment
      name: airflow-webserver
      namespace: airflow
    - kind: Deployment
      name: airflow-scheduler
      namespace: airflow

# ---
# # Configuration: Example DAGs
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: foundation-airflow-dags
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: foundation-airflow
#   interval: 10m
#   retryInterval: 1m
#   timeout: 10m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system-airflow
#   path: ./software/stacks/foundation/airflow/dags
#   prune: true
#   wait: true
