apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-ingress.yaml
  - website-deployment.yaml
  - website-service.yaml
  - website-ingress.yaml
