apiVersion: hostk8s.io/v1
kind: SecretContract
metadata:
  name: foundation/redis
spec:
  secrets:
    - name: redis-commander-credentials
      namespace: redis
      data:
        - key: username
          value: admin
        - key: password
          generate: password
          length: 12
