apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m
  url: ${GITOPS_REPO}
  ref:
    branch: ${GITOPS_BRANCH}
  ignore: |
    # exclude all
    /*
    # include shared components and this stack
    !/software/components/
    !/software/stacks/voting-app/
