######################
## Sample Stamp Applications
######################
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample-applications
  namespace: flux-system
spec:
  dependsOn:
    - name: component-cert-manager
    - name: component-cert-manager-certs
    - name: component-registry
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: sample-repo
  path: ./software/stamp/sample/applications
  prune: true
  wait: true
