apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-certs
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: "./software/components/cert-manager/certs"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: osdu-ci-repo
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: ca-key-pair
      namespace: cert-manager
