apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostk8s-vote
  namespace: sample-voting
  labels:
    hostk8s.app: hostk8s-vote
    hostk8s.component: voting-system
    hostk8s.tutorial: level-100
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hostk8s-vote
  template:
    metadata:
      labels:
        app: hostk8s-vote
        hostk8s.app: hostk8s-vote
    spec:
      containers:
      - name: vote
        image: localhost:5000/hostk8s-vote:latest
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "redis-infrastructure.redis-infrastructure.svc.cluster.local"
        - name: OPTION_A
          value: "Kubernetes"
        - name: OPTION_B
          value: "Docker Swarm"
        - name: FLASK_DEBUG
          value: "false"
        - name: PORT
          value: "80"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hostk8s-vote
  namespace: sample-voting
  labels:
    hostk8s.app: hostk8s-vote
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: hostk8s-vote
  type: ClusterIP
